# **Theoretical Questions**

# Question 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations ?

**Answer:**   
### The Purpose of NumPy

NumPy, short for **Numerical Python**, is a core library in Python for scientific computing. Its main purpose is to provide a powerful and efficient **multidimensional array object**, called `ndarray`, which is essential for numerical operations. It serves as the foundation for many other scientific and data analysis libraries, such as SciPy and Pandas.

***

### Advantages of NumPy

* **Performance:** NumPy arrays are much faster than standard Python lists for numerical operations. This is because the core of NumPy is written in C and Fortran, allowing it to perform computations on large datasets with incredible speed.
* **Memory Efficiency:** NumPy arrays are more memory-efficient than Python lists. They store data in a contiguous block of memory and are of a single data type, which reduces memory usage and improves performance.
* **Powerful Functions:** NumPy provides a vast collection of mathematical functions for linear algebra, Fourier transforms, and random number generation, which can be applied to entire arrays without needing slow Python loops.
* **Vectorization:** NumPy enables **vectorization**, which means you can perform operations on entire arrays at once, rather than element by element. This makes code cleaner, more concise, and much faster.

***

### How NumPy Enhances Python's Capabilities

Python's built-in lists are flexible but not optimized for numerical tasks. NumPy enhances Python by introducing the `ndarray` object, which is a specialized, high-performance data structure. It allows you to:

* **Perform vectorized operations:** Instead of writing a loop to add two lists, you can simply add two NumPy arrays directly (e.g., `array1 + array2`), which is significantly faster.
* **Use broadcasting:** This feature allows you to perform operations on arrays of different sizes. For example, you can add a single number to every element of an array without a loop.
* **Handle large datasets efficiently:** For tasks in data science, machine learning, and scientific research, where you deal with millions of data points, NumPy's speed and memory efficiency are crucial. It allows Python to compete with languages like MATLAB and R for these types of tasks.

# Question 2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?

**Answer:**

NumPy's `np.mean()` and `np.average()` are both used to compute the average of a dataset, but they have a key difference. While `np.mean()` calculates the **arithmetic mean** (the sum of all values divided by the number of values), `np.average()` can calculate a **weighted average** in addition to the arithmetic mean.

***

### np.mean()

* **Purpose:** Calculates the arithmetic mean.
* **Parameters:** It takes an array-like object and an optional `axis` parameter to specify the axis along which to compute the mean.
* **Usage:** You'd use `np.mean()` for simple, unweighted averages, which is the most common use case. For example, finding the average score of a class or the average temperature over a week.

***

### np.average()

* **Purpose:** Calculates the arithmetic mean or a **weighted average**.
* **Parameters:** It takes the same parameters as `np.mean()` (`a`, `axis`) but also includes an optional `weights` parameter. This `weights` parameter is an array of the same size as the input array, where each value corresponds to the weight of the element at that index.
* **Usage:** You'd use `np.average()` when certain data points are more significant than others and should contribute more to the final average. For instance, calculating the average grade where an exam is worth more than a quiz, or finding the average stock price of a company considering the number of shares traded at each price.

***

### When to Use Which?

* **Use `np.mean()`** for all cases where you need a simple, unweighted average. It's often the default choice due to its directness and simplicity.
* **Use `np.average()`** specifically when you need to calculate a **weighted average**. If you don't provide the `weights` parameter, `np.average()` will return the same result as `np.mean()`.

In summary, `np.average()` is a more versatile function because it can handle weighted averages, while `np.mean()` is a more specialized function for a single type of calculation. If you don't need weighting, `np.mean()` is the better choice as it's more explicit about its purpose.

# Question 3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

**Answer:**

NumPy arrays can be reversed along different axes using a variety of methods, with **slicing** being the most common and versatile.

## Reversing a 1D Array

For a one-dimensional array, the simplest way to reverse it is by using slicing with a step of `-1`. This creates a new view of the array in reverse order.

**Method:** Slicing `[::-1]`

```python
import numpy as np

# Create a 1D array
arr_1d = np.array([1, 2, 3, 4, 5])

# Reverse the array
reversed_arr_1d = arr_1d[::-1]

print(f"Original 1D array: {arr_1d}")
print(f"Reversed 1D array: {reversed_arr_1d}")
```

**Output:**

```
Original 1D array: [1 2 3 4 5]
Reversed 1D array: [5 4 3 2 1]
```

-----

## Reversing a 2D Array

For a two-dimensional array, you can reverse it along different axes (rows or columns) or along both.

### Reversing Rows (Vertical Flip)

To reverse the rows of a 2D array, you apply the same `[::-1]` slice to the first dimension (the rows). This is equivalent to a vertical flip.

**Method:** Slicing `[::-1, :]` or `np.flipud()`

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the rows
reversed_rows = arr_2d[::-1, :]

print("Original 2D array:")
print(arr_2d)
print("\n2D array with rows reversed:")
print(reversed_rows)
```

**Output:**

```
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D array with rows reversed:
[[7 8 9]
 [4 5 6]
 [1 2 3]]
```

-----

### Reversing Columns (Horizontal Flip)

To reverse the columns of a 2D array, you apply the `[::-1]` slice to the second dimension (the columns). This is equivalent to a horizontal flip.

**Method:** Slicing `[:, ::-1]` or `np.fliplr()`

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse the columns
reversed_cols = arr_2d[:, ::-1]

print("Original 2D array:")
print(arr_2d)
print("\n2D array with columns reversed:")
print(reversed_cols)
```

**Output:**

```
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D array with columns reversed:
[[3 2 1]
 [6 5 4]
 [9 8 7]]
```

-----

### Reversing Both Rows and Columns

To reverse the entire array (both rows and columns), you can apply the `[::-1]` slice to both dimensions.

**Method:** Slicing `[::-1, ::-1]`

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Reverse both rows and columns
reversed_both = arr_2d[::-1, ::-1]

print("Original 2D array:")
print(arr_2d)
print("\n2D array with both rows and columns reversed:")
print(reversed_both)
```

**Output:**

```
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

2D array with both rows and columns reversed:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
```

# Question 4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

**Answer:**
You can determine the data type of elements in a NumPy array using the `.dtype` attribute. This attribute returns a data-type object that describes the kind of elements in the array.

### Determining the Data Type

The most direct way to check the data type is to access the `.dtype` attribute of the NumPy array object.

```python
import numpy as np

# Create an array with integer elements
int_array = np.array([1, 2, 3])
print(f"Data type of int_array: {int_array.dtype}")

# Create an array with floating-point elements
float_array = np.array([1.0, 2.5, 3.7])
print(f"Data type of float_array: {float_array.dtype}")

# Create an array with string elements
string_array = np.array(['a', 'b', 'c'])
print(f"Data type of string_array: {string_array.dtype}")
```

**Output:**

```
Data type of int_array: int64
Data type of float_array: float64
Data type of string_array: <U1
```

-----

### Importance of Data Types

Data types in NumPy are crucial for both **memory management** and **performance**. Unlike Python's built-in lists which can store different data types, NumPy arrays are **homogeneous**, meaning all elements must be of the same type. This homogeneity is the foundation of NumPy's efficiency.

  * **Memory Management:** Specifying a data type allows NumPy to allocate a fixed-size block of memory for the entire array. For example, a 64-bit integer (`int64`) takes up 8 bytes of memory, so an array of 1,000 integers will always occupy 8,000 bytes. This predictable allocation is much more efficient than a Python list, where each element is a separate object with its own memory overhead. By choosing the smallest data type that fits your data (e.g., `int8` instead of `int64` if your values are small), you can significantly reduce the memory footprint of large arrays.

  * **Performance:** The fixed size and contiguous memory layout of NumPy arrays enable highly optimized, **vectorized operations**. When NumPy knows the data type, it can use low-level C and Fortran routines that are designed to perform operations on a block of memory very quickly, without having to check the type of each individual element. This leads to a massive performance boost, especially for large-scale numerical computations like matrix multiplication or element-wise arithmetic. The consistent data type allows NumPy to apply operations to the entire array at once, rather than using slow Python loops.

# Question 5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

**Answer:**
### Defining ndarrays

An **ndarray** is the fundamental data structure in NumPy. It's a **multidimensional array object** used to store a collection of items of the **same data type**. This structure is a powerful and efficient way to handle large datasets in Python, forming the basis for most scientific computing and data analysis operations.

---
### Key Features of ndarrays

* **Homogeneous:** All elements in an ndarray must be of the same data type (e.g., all integers, all floats). This uniformity allows for highly optimized operations and efficient memory usage.
* **Multidimensional:** ndarrays can have any number of dimensions, from a 1D array (vector) to a 2D array (matrix) or higher. This makes them ideal for representing various forms of data, such as images, time series, or tensors in machine learning.
* **Vectorized Operations:** NumPy allows you to perform operations on entire arrays at once without the need for explicit loops. For example, adding two arrays `A + B` performs element-wise addition, which is much faster than a loop.
* **Efficient Memory:** ndarrays store data in a contiguous block of memory. This allows for fast data access and manipulation, a key reason for their superior performance compared to Python lists.
* **Broadcasting:** This feature allows NumPy to perform operations on arrays with different shapes. For example, you can add a single number to every element of an array, which is a powerful and convenient feature.

---
### Differences from Standard Python Lists

| Feature | NumPy ndarray | Python List |
| :--- | :--- | :--- |
| **Data Type** | **Homogeneous:** All elements must have the same data type. | **Heterogeneous:** Can store elements of different data types. |
| **Performance** | **Much faster** for numerical operations due to being written in C and Fortran. | **Slower** for numerical operations due to dynamic typing and overhead. |
| **Memory Usage** | **More memory-efficient** due to storing elements in a contiguous memory block. | **Less memory-efficient** as it stores pointers to objects scattered in memory. |
| **Functionality** | Built-in support for advanced mathematical operations like linear algebra, statistics, and broadcasting. | Lacks built-in support for high-performance numerical operations. |
| **Usage** | Ideal for numerical and scientific computations. | General-purpose container for any type of data. |

# Question 6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

**Answer:** The performance benefits of NumPy arrays over Python lists for large-scale numerical operations are significant and stem from three main reasons: **data type homogeneity**, **contiguous memory allocation**, and the use of **vectorized operations**.

---
### Data Type Homogeneity and Memory Efficiency

Unlike Python lists, which can hold elements of different data types, all elements in a NumPy array must be of the same type (e.g., all integers or all floats). This homogeneity allows NumPy to be much more memory-efficient. A Python list stores pointers to objects, which can be scattered throughout memory, leading to overhead. In contrast, a NumPy array stores its elements in a single, contiguous block of memory. This packed data structure reduces memory usage and enables faster data access and manipulation.

---
### Vectorized Operations

NumPy leverages **vectorization**, which means that operations are performed on entire arrays at once, rather than on individual elements using a loop. These operations are implemented in low-level, pre-compiled C and Fortran code, which is significantly faster than Python's interpreted loops. For example, adding two large arrays `array1 + array2` is a single, fast operation in NumPy, whereas doing the same with Python lists would require a slow, explicit `for` loop.

---
### Performance Breakdown

For a large numerical task, such as adding two arrays with a million elements:

* **Python List:** The interpreter has to repeatedly access each element, check its type, and perform the addition one by one. This process involves a lot of overhead and is very slow.
* **NumPy Array:** The operation is handed off to a pre-compiled C function. This function works directly on the contiguous block of memory, applying the addition operation to all elements in one highly efficient pass. The result is a performance gain that can be **orders of magnitude faster** than the Python list equivalent. This efficiency makes NumPy an indispensable tool for scientific computing, machine learning, and data analysis where large datasets are the norm.

# Question 7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

**Answer:**
`vstack()` and `hstack()` are NumPy functions used to stack arrays. The key difference lies in the direction of stacking: **`vstack()` stacks arrays vertically (row-wise)**, while **`hstack()` stacks them horizontally (column-wise)**.

-----

### vstack()

The `vstack()` function stacks arrays in sequence vertically (row-wise). This means it adds arrays as new rows to form a larger array. For this to work, the arrays must have the same number of columns.

**Example:**

```python
import numpy as np

# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Vertically stack the arrays
v_stack = np.vstack((a, b))

print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nResult of vstack():")
print(v_stack)
```

**Output:**

```
Array a:
[1 2 3]

Array b:
[4 5 6]

Result of vstack():
[[1 2 3]
 [4 5 6]]
```

-----

### hstack()

The `hstack()` function stacks arrays in sequence horizontally (column-wise). This means it adds arrays as new columns to form a larger array. For this to work, the arrays must have the same number of rows.

**Example:**

```python
import numpy as np

# Create two 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Horizontally stack the arrays
h_stack = np.hstack((a, b))

print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nResult of hstack():")
print(h_stack)
```

**Output:**

```
Array a:
[1 2 3]

Array b:
[4 5 6]

Result of hstack():
[1 2 3 4 5 6]
```

For multi-dimensional arrays, the logic remains the same:

  * `vstack()` combines them row-wise, increasing the number of rows.
  * `hstack()` combines them column-wise, increasing the number of columns.

# Question 8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

**Answer:**
`fliplr()` and `flipud()` are NumPy functions used to reverse the order of elements in an array, but they do so along different axes. **`fliplr()` performs a horizontal flip**, reversing the order of columns, while **`flipud()` performs a vertical flip**, reversing the order of rows.

-----

### fliplr() (Flip Left-Right)

`fliplr()` reverses the elements along the horizontal axis (axis 1). This is equivalent to flipping the array from left to right. It is primarily used for 2D arrays and higher. If used on a 1D array, it will simply reverse the array's elements.

**Example with a 2D Array:**

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip the array horizontally
flipped_lr = np.fliplr(arr_2d)

print("Original 2D array:")
print(arr_2d)
print("\nFlipped Left-Right (fliplr):")
print(flipped_lr)
```

**Output:**

```
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Left-Right (fliplr):
[[3 2 1]
 [6 5 4]
 [9 8 7]]
```

-----

### flipud() (Flip Up-Down)

`flipud()` reverses the elements along the vertical axis (axis 0). This is equivalent to flipping the array from top to bottom. Like `fliplr()`, it is most commonly used for 2D arrays and above, but it will also reverse a 1D array.

**Example with a 2D Array:**

```python
import numpy as np

# Create a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Flip the array vertically
flipped_ud = np.flipud(arr_2d)

print("Original 2D array:")
print(arr_2d)
print("\nFlipped Up-Down (flipud):")
print(flipped_ud)
```

**Output:**

```
Original 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Flipped Up-Down (flipud):
[[7 8 9]
 [4 5 6]
 [1 2 3]]
```


# Question 9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

**Answer:**
The `array_split()` method in NumPy is used to **split an array into multiple sub-arrays of equal or near-equal size**. It's a more flexible alternative to `split()` because it can handle uneven divisions without raising an error.

-----

### Functionality of `array_split()`

The `array_split()` method takes three main arguments:

1.  **`ary`**: The array to be split.
2.  **`indices_or_sections`**: The number of sections to split the array into. This can be an integer, which specifies the number of equal divisions, or a list of indices, which specifies the points at which to split the array.
3.  **`axis`**: The axis along which to split the array (default is 0).

`array_split()` divides an array into a specified number of sub-arrays. For a 1D array, this means creating a list of smaller arrays. For a 2D array, it can be used to split the rows or columns.

-----

### Handling Uneven Splits

This is where `array_split()` really shines. If the number of elements in the array is not perfectly divisible by the number of sections, `array_split()` will **distribute the remaining elements among the first few sub-arrays**. It does this without raising a `ValueError`, which `np.split()` would do.

**Example with an Uneven Split:**
Let's split an array of 7 elements into 3 sections. The division is 7 / 3, which is 2 with a remainder of 1. `array_split()` will distribute this remainder.

```python
import numpy as np

# Create a 1D array with 7 elements
arr = np.arange(7)

# Split the array into 3 sections
split_arr = np.array_split(arr, 3)

print(f"Original array: {arr}")
print(f"Split sections: {split_arr}")
```

**Output:**

```
Original array: [0 1 2 3 4 5 6]
Split sections: [array([0, 1, 2]), array([3, 4]), array([5, 6])]
```

In this example, the first sub-array gets an extra element from the remainder, resulting in sections of sizes 3, 2, and 2. The distribution ensures that the sub-arrays are as balanced in size as possible.

# Question 10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

**Answer:**
Vectorization and broadcasting are two core concepts in NumPy that enable highly efficient array operations. They allow you to perform calculations on entire arrays at once, eliminating the need for slow Python loops.

### Vectorization

**Vectorization** is the process of performing an operation on an entire array, or a pair of arrays, at once without using an explicit Python loop. NumPy achieves this by using highly optimized, pre-compiled C and Fortran code behind the scenes.

For example, to add two arrays `A` and `B`, you simply write `C = A + B`. NumPy's vectorized operation handles the element-by-element addition for you, which is much faster than writing a `for` loop to iterate through each element and add them individually. This approach not only speeds up computations but also makes the code cleaner and more readable.

-----

### Broadcasting

**Broadcasting** is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. It's the process by which NumPy automatically "stretches" or "duplicates" the smaller array to match the shape of the larger array for an element-wise operation, without actually making copies in memory.

A common example is adding a scalar (a single number) to a NumPy array.

```python
import numpy as np

arr = np.array([10, 20, 30])
result = arr + 5

print(result)
```

**Output:**

```
[15 25 35]
```

Here, NumPy broadcasts the scalar `5` so it can be added to each element of the array `arr`.

Broadcasting also works with arrays of different dimensions, as long as their shapes are compatible. Two dimensions are compatible if they are equal, or if one of them is 1.

-----

### Contribution to Efficiency

Vectorization and broadcasting are crucial for efficient array operations because they:

  * **Eliminate Python Loops:** Python's loops are notoriously slow due to the interpreter's overhead. By using vectorized operations, you hand the work over to fast, compiled code.
  * **Reduce Memory Usage:** Broadcasting avoids creating unnecessary copies of data. Instead of making a new, larger array to match a smaller one, it simply uses a smarter internal mechanism to perform the operation.
  * **Simplify Code:** These concepts lead to more concise and readable code, reducing the risk of errors that can arise from manual loops and indexing.

In essence, these features make NumPy the go-to library for numerical computing in Python, allowing it to handle massive datasets with performance comparable to lower-level languages.

# **Practical Question**

**1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.**

In [3]:
# 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

import numpy as np

arr = np.random.randint(1, 101, (3, 3))
print("Original array:")
print(arr)

# Interchange rows and columns (transpose)
transposed_arr = arr.T
print("\nArray with rows and columns interchanged:")
print(transposed_arr)

Original array:
[[83 10 51]
 [42 33 10]
 [38 33 31]]

Array with rows and columns interchanged:
[[83 42 38]
 [10 33 33]
 [51 10 31]]


**2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.**

In [5]:
# 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

arr = np.arange(10)
print("Original 1D array: ", arr)

arr = arr.reshape(2,5)
print("Reshaped 2x5 array: ", arr)

arr = arr.reshape(5,2)
print("Reshaped 5x2 array: ", arr)

Original 1D array:  [0 1 2 3 4 5 6 7 8 9]
Reshaped 2x5 array:  [[0 1 2 3 4]
 [5 6 7 8 9]]
Reshaped 5x2 array:  [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


**3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.**

In [7]:
# 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

import numpy as np

arr = np.random.rand(4, 4)
print("Original 4x4 array:")
print(arr)

# Add a border of zeros
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nArray with zero border:")
print(padded_arr)

Original 4x4 array:
[[0.1765949  0.12695551 0.38289623 0.97715615]
 [0.39044716 0.31372021 0.48036106 0.15723873]
 [0.6838331  0.62118433 0.64137105 0.01285373]
 [0.70698327 0.06928245 0.06334848 0.28915062]]

Array with zero border:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.1765949  0.12695551 0.38289623 0.97715615 0.        ]
 [0.         0.39044716 0.31372021 0.48036106 0.15723873 0.        ]
 [0.         0.6838331  0.62118433 0.64137105 0.01285373 0.        ]
 [0.         0.70698327 0.06928245 0.06334848 0.28915062 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


**4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.**

In [10]:
# 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.
arr = np.arange(10, 61, 5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

**5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.**



In [11]:
# 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

import numpy as np

arr = np.array(['python', 'numpy', 'pandas'])

for i in arr:
  print(f"Original string: {i}")
  print(f"Uppercase: {i.upper()}")
  print(f"Lowercase: {i.lower()}")
  print(f"Titlecase: {i.title()}")

Original string: python
Uppercase: PYTHON
Lowercase: python
Titlecase: Python
Original string: numpy
Uppercase: NUMPY
Lowercase: numpy
Titlecase: Numpy
Original string: pandas
Uppercase: PANDAS
Lowercase: pandas
Titlecase: Pandas


**6. Generate a NumPy array of words. Insert a space between each character of every word in the array.**

In [12]:
# 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

import numpy as np

# Generate a NumPy array of words
word_array = np.array(['hello', 'world', 'numpy', 'python'])

print("Original array:")
print(word_array)

# Insert a space between each character of every word
spaced_words = np.array([' '.join(word) for word in word_array])

print("\nArray with spaces between characters:")
print(spaced_words)

Original array:
['hello' 'world' 'numpy' 'python']

Array with spaces between characters:
['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


**7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.**

In [13]:
# 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

# Element-wise addition
addition_result = array1 + array2
print("\nElement-wise addition:")
print(addition_result)

# Element-wise subtraction
subtraction_result = array1 - array2
print("\nElement-wise subtraction:")
print(subtraction_result)

# Element-wise multiplication
multiplication_result = array1 * array2
print("\nElement-wise multiplication:")
print(multiplication_result)

# Element-wise division
division_result = array1 / array2
print("\nElement-wise division:")
print(division_result)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Element-wise addition:
[[ 6  8]
 [10 12]]

Element-wise subtraction:
[[-4 -4]
 [-4 -4]]

Element-wise multiplication:
[[ 5 12]
 [21 32]]

Element-wise division:
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


**8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.**

In [15]:
# 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


**9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array**

In [20]:
# 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array
prime_arr = np.random.randint(0, 1001, 100)
print(prime_arr)

# Find and display the prime numbers
# prime_numbers
for num in prime_arr:
    if num > 1:
        for i in range(2, num-1):
            if num % i == 0:
                break
        else:
            print(num)

[867 420 242 507 315   5 372 243 316 494 725 764 913 311 965 141 776 922
 670 399 978 536 568 638 987 424 186 800 269 140 953 437 454 538 130 905
 455 204 382 638  23 725 576 122 513 779  45 245 964 420 103 659 767 686
 291 351 636 868 804 168 817 397 519   2 484 791 968 517 847 251 458 146
 388 105 618 231 748 410 856  52 375 556 543 208  11 317 301  54 436  83
 565 814 335 232 708 515 102 257 132 415]
5
311
269
953
23
103
659
397
2
251
11
317
83
257


**10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.**

In [23]:
# 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

import numpy as np

# Create a NumPy array representing daily temperatures for a month
# Let's assume a month with 30 days for simplicity
daily_temperatures = np.random.randint(15, 30, 30) # Generating random temperatures between 15 and 30

print("Daily Temperatures for the month:")
print(daily_temperatures)

# Option 1: Assuming a month with 28 days for simplicity in reshaping
if len(daily_temperatures) >= 28:
    weekly_temperatures = daily_temperatures[:28].reshape(-1, 7)
    print("\nWeekly Temperatures (reshaped for 4 weeks):")
    print(weekly_temperatures)

    # Calculate weekly averages
    weekly_averages = np.mean(weekly_temperatures, axis=1)
    print("\nWeekly Averages:")
    print(weekly_averages)
else:
    print("\nArray is too short to calculate full weekly averages.")


Daily Temperatures for the month:
[17 23 29 19 21 24 26 20 21 20 16 27 23 25 25 15 15 15 22 21 22 26 29 22
 21 28 27 15 15 23]

Weekly Temperatures (reshaped for 4 weeks):
[[17 23 29 19 21 24 26]
 [20 21 20 16 27 23 25]
 [25 15 15 15 22 21 22]
 [26 29 22 21 28 27 15]]

Weekly Averages:
[22.71428571 21.71428571 19.28571429 24.        ]
